### Initialize MCP session
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json

{
  "jsonrpc": "2.0",
  "id": "{{$random.uuid}}",
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-11-25",
    "capabilities": {}
  }
}

### Notify initialized
@mcpSessionId = 1bdb1d18-f46a-4a96-97ad-f1c361c5898e
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json
Mcp-Session-Id: {{mcpSessionId}}

{
  "jsonrpc": "2.0",
  "method": "notifications/initialized"
}

### Ping
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json
Mcp-Session-Id: {{mcpSessionId}}

{
  "jsonrpc": "2.0",
  "id": "{{$random.uuid}}",
  "method": "ping"
}

### List tools
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json
Mcp-Session-Id: {{mcpSessionId}}

{
  "jsonrpc": "2.0",
  "id": "{{$random.uuid}}",
  "method": "tools/list"
}

### Call list-pizzas
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json
Mcp-Session-Id: {{mcpSessionId}}

{
  "jsonrpc": "2.0",
  "id": "{{$random.uuid}}",
  "method": "tools/call",
  "params": {
    "name": "list-pizzas",
    "arguments": {}
  }
}

### Call order-pizzas
POST {{host}}/mcp
Content-Type: application/json
Accept: text/event-stream, application/json
Mcp-Session-Id: {{mcpSessionId}}

{
  "jsonrpc": "2.0",
  "id": "{{$random.uuid}}",
  "method": "tools/call",
  "params": {
    "name": "order-pizzas",
    "arguments": {
      "pizzaIds": ["margherita", "pepperoni"]
    }
  }
}
