spring.application.name=wjug
spring.jackson.default-property-inclusion=non_null
spring.output.ansi.enabled=always
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
# TODO Remove after official Spring AI 2.0.0 release
logging.level.org.apache.tomcat.util.net.NioEndpoint=OFF
logging.level.org.springframework.context.support.PostProcessorRegistrationDelegate=ERROR
