spring.application.name=wjug

spring.mvc.problemdetails.enabled=true

spring.output.ansi.console-available=true

management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health
