spring.application.name=wjug
spring.jackson.default-property-inclusion=non_null
spring.output.ansi.console-available=true
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health
